// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdmmqkxcgygdlzkdhoem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkbW1xa3hjZ3lnZGx6a2Rob2VtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NzUxNjAsImV4cCI6MjA1NzU1MTE2MH0.NgPmNOsUymPQH-2csTQxYQldv_xNadBxZocawF_TLrw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);